# Generated by Django 4.2.6 on 2023-10-26 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True)),
                ('customer_profile_pic', models.ImageField(upload_to='customer/profile_pic/')),
                ('address', models.TextField()),
                ('address_district', models.CharField(blank=True, max_length=40, null=True)),
                ('address_country', models.CharField(blank=True, max_length=40, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=400)),
                ('otp_token', models.CharField(blank=True, max_length=400)),
                ('is_customer', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shop_name', models.CharField(max_length=300, unique=True)),
                ('shop_created', models.DateField(auto_now_add=True)),
                ('shop_address', models.TextField()),
                ('shop_logo', models.ImageField(blank=True, upload_to='seller/shop_logo')),
                ('shop_banner', models.ImageField(blank=True, upload_to='seller/shop_banner')),
                ('auth_token', models.CharField(blank=True, max_length=400)),
                ('otp_token', models.CharField(blank=True, max_length=400)),
                ('is_seller', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True)),
                ('auth_token', models.CharField(blank=True, max_length=400)),
                ('otp_token', models.CharField(blank=True, max_length=400)),
                ('is_officestaff', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
    ]
