# Generated by Django 4.2.6 on 2023-10-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customer_auth_token_alter_customer_otp_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='staff',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
