# Generated by Django 4.2.6 on 2023-11-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_order_id_alter_order_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(db_index=True, default=52810068, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(to='order.orderitem'),
        ),
    ]
