# Generated by Django 4.2.6 on 2023-11-03 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_order_id_alter_order_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(db_index=True, default=uuid.UUID('a3980b4a-aa1a-4694-b8a5-a05c6dd923cc'), editable=False, unique=True),
        ),
    ]
