# Generated by Django 4.2.6 on 2023-11-03 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_index=True, default=uuid.UUID('a13e3907-35ee-403e-ba84-54d270ee5c00'), editable=False, max_length=10, unique=True),
        ),
    ]
